### ISSUE TITLE
createFrom changes subfield ordering

### ISSUE THREAD

**Issue by tvirolai** [NatLibFi/marc-record-merge#44]
createFrom seems to mess the ordering of subfields in a field in some cases.

Here's an example case:

`"490": { "action": "createFrom", "options": { "subfields": { "a": {},  "x": { "modifications": [ { "type": "replace", "args": [/[0-9-]+/, ""] } ] }, "v": {} } } }`

It should create a new 490 that should otherwise be identical to the 490 in the source record, except that the ISSN code in $x should be emptied. Here the ordering of the subfields changes from $a $x $v to $a $v $x, i.e. the changed subfield is moved last.

**Comment by aduroo** [comment]
https://github.com/NatLibFi/marc-record-merge/pull/45
